---
  # This syntax is for ansible 2.2
- hosts: all
  tasks:
  - name: Restart server
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    become: yes
    become_method: sudo
    ignore_errors: true
  - name: Wait for server to respond to SSH after reboot
    local_action: wait_for host="{{ inventory_hostname }}" state=started port=22 delay=30 timeout=300 connect_timeout=15
